spring:
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  application:
    name: vicon
  redis:
    host: localhost
    database: 0
    port: 6379
    password: 
    pool:
      max-active: 5000
      max-wait: -1
      max-idle: 8
    timeout: 0
  aop:
    auto: true


mybatis:
  mapperLocations: classpath:mapper/**/*.xml

logging:
  config: classpath:logback.xml




